---
abstract: 'MagicEnvelopes for the Salmon Protocol'
author:
  - 'Nils Diewald'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-MagicSignatures-Envelope
no_index:
  directory:
    - t
    - inc
recommends:
  Math::BigInt::GMP: '0'
  Math::Prime::Util::GMP: '0.18'
  Math::Random::ISAAC::XS: '1.004'
requires:
  Carp: '0'
  Crypt::MagicSignatures::Key: '0.13'
  Mojolicious: '4.23'
  perl: '5.010001'
resources:
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/Akron/Crypt-MagicSignatures-Envelope
version: '0.07'
